# Build stage
FROM node:18-alpine3.18 as build-stage
WORKDIR /app
COPY package*.json ./
COPY . .


ARG VITE_API_KEY 
ARG VITE_AUTH_DOMAIN
ARG VITE_PROJECT_ID
ARG VITE_STORAGE_BUCKET
ARG VITE_MESSAGING_SENDER_ID
ARG VITE_APP_ID
ARG VITE_MEASUREMENT_ID


ENV VITE_API_KEY =${VITE_API_KEY}
ENV VITE_AUTH_DOMAIN =${VITE_AUTH_DOMAIN}
ENV VITE_PROJECT_ID =${VITE_PROJECT_ID}
ENV VITE_STORAGE_BUCKET =${VITE_STORAGE_BUCKET}
ENV VITE_MESSAGING_SENDER_ID =${VITE_MESSAGING_SENDER_ID}
ENV VITE_APP_ID =${VITE_APP_ID}
ENV VITE_MEASUREMENT_ID =${VITE_MEASUREMENT_ID}




RUN npm install
RUN npm run build

# Production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html  
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
