export {default as angry} from "./angry.svg"
export {default as care} from "./care.svg"
export {default as like} from "./like.svg"
export {default as love} from "./love.svg"
export {default as worldicon} from "./world-icon.svg"
export {default as emptylike} from "./like-empty.svg"
export {default as emptycomment} from "./comment-empty.svg"