name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set app version
        id: set_version
        run: echo "::set-output name=appver::$(node -e 'console.log(require("./package.json").version)')"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: halitderya/fbclone:${{ steps.set_version.outputs.appver }}-64
          platforms: linux/amd64
          file: ./Dockerfile

      - name: Deploying
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker container stop fbclone
            docker container rm fbclone
            docker rmi $(docker images halitderya/fbclone -aq) --force
            docker image pull halitderya/fbclone:${{ steps.set_version.outputs.appver }}-64
            docker container run -d --name fbclone -p 3001:80 halitderya/fbclone:${{ steps.set_version.outputs.appver }}-64
